### ISSUE TITLE
Set a suitable background-color in light theme

### ISSUE THREAD

**Issue by joy-yu** [Gerrnperl/outline-map#4]
![image](https://user-images.githubusercontent.com/9348314/181177844-2b65ed09-dbcc-499b-aaad-5035106216d4.png)

**Comment by Gerrnperl** [comment]
What is your color theme? the default light?

**Comment by joy-yu** [comment]
Atom One Light Theme @Gerrnperl

**Comment by Gerrnperl** [comment]
I didn't reassign the background color due to differences in different color themes.

In new version v0.5.2 two items in configuration: `outline-map.color` : `visibleRange` and `focusingItem` have been added

Now you can specify the background-color.
![Screenshot_20220727_162100](https://user-images.githubusercontent.com/64595686/181200810-e9a24851-b683-4f77-aa9a-286a757cdd3f.png)
