### ISSUE TITLE
My (custom) code syntax highlight for my Theme doesnt show properly.

### ISSUE THREAD

**Issue by Norlandz** [Gerrnperl/outline-map#49]
### Describe the bug
After a recent update. 
When I turn on the Extension. (All other Extensions are off.)
My (custom) **code syntax highlight** for my Theme **doesnt show properly**. 

### Current behavior
![image](https://github.com/Gerrnperl/outline-map/assets/43581880/1699309b-28d8-45bf-b734-d2f1c89e6995)

### Expected behavior
![image](https://github.com/Gerrnperl/outline-map/assets/43581880/03bc1e79-2e44-45f6-9664-fcc247684316)

### misc (my custom syntax setting, but doesnt really matter, the built-in syntax seems also wrong)
```json
  "editor.semanticTokenColorCustomizations": {
    "[Default Dark+]": {
      "enabled": true,
      "rules": {
        "parameter": {
          "foreground": "#6ac7d4",
          "italic": true
        },
        "property.static": {
          "foreground": "#59a6f8",
          "bold": false
        },
      }
    }
  },
```

### env & device
 - OS: Windows
 - Version v1.2.1

**Comment by Gerrnperl** [comment]
This bug occurs because of conflicts among multiple semantic token providers. 

I previously thought that vscode would merge the semantic tokens provided by all providers (just like the document symbol provider), but vscode only sorted and selected one. 

I'm trying to use other methods for syntax highlighting. Please **set `outline-map.region.highlight` to `false`** to avoid conflicts until I fix it.

**Comment by Gerrnperl** [comment]
Fixed.
![Screenshot_20231021_132111](https://github.com/Gerrnperl/outline-map/assets/64595686/cae494c3-f799-4a4e-93b5-4ab534193376)
